apiVersion: apps/v1
kind: Deployment
metadata:
  name: combined-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-service
  template:
    metadata:
      labels:
        app: combined-service
    spec:
      containers:
        - name: book-service
          image: book-service:4.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8080
        - name: sidecar-service
          image: sidecar-service:4.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: log-volume
              mountPath: /logs
          ports:
            - containerPort: 8081
      volumes:
        - name: log-volume
          emptyDir: {}
